Django/anfisa1sprint/anfisa_for_friends/about/urls.py
from django.urls import path
from .views import Description

app_name = 'about'

urlpatterns = [
    path('', Description.as_view(), name='description'),
]

Django/anfisa1sprint/anfisa_for_friends/anfisa_for_friends/urls.py
from django.contrib import admin
from django.contrib.auth.forms import UserCreationForm
from django.views.generic.edit import CreateView
from django.urls import include, path, reverse_lazy 
from django.conf import settings

urlpatterns = [
    path('', include('homepage.urls', namespace='homepage')),
    path('about/', include('about.urls', namespace='about')),
    path('ice_cream/', include('ice_cream.urls', namespace='ice_cream')),
    path('contest/', include('contest.urls')),
    path('admin/', admin.site.urls),
    path('auth/', include('django.contrib.auth.urls')), 
    path(
        'auth/registration/', 
        CreateView.as_view(
            template_name='registration/registration_form.html',
            form_class=UserCreationForm,
            success_url=reverse_lazy('pages:homepage'),
        ),
        name='registration',
    ),
] 

# Если проект запущен в режиме разработки...
if settings.DEBUG:
    import debug_toolbar
    # Добавить к списку urlpatterns список адресов из приложения debug_toolbar:
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),) 

Django/anfisa1sprint/anfisa_for_friends/contest/urls.py
from django.urls import path

from . import views

app_name = 'contest'

urlpatterns = [
    path('', views.proposal, name='create'),
    path('list/', views.proposal_list, name='list'),
    path('<int:pk>/edit/', views.proposal, name='edit'),
    path('<int:pk>/delete/', views.delete_proposal, name='delete'), 
    path('login_only/', views.simple_view), 
]

Django/anfisa1sprint/anfisa_for_friends/contest/models.py
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models 
from django.contrib.auth import get_user_model 

User = get_user_model()

class Contest(models.Model):
    author = models.ForeignKey(
        User, verbose_name='Автор записи', on_delete=models.CASCADE, null=True
    )
    title = models.CharField(verbose_name='Название', max_length=20)
    description = models.TextField(verbose_name='Описание')
    price = models.IntegerField(
        verbose_name='Цена',
        validators=[MinValueValidator(10), MaxValueValidator(100)],
        help_text='Рекомендованная розничная цена',
    )
    comment = models.TextField(verbose_name='Комментарий', blank=True)

Django/anfisa1sprint/anfisa_for_friends/contest/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.core.mail import send_mail

from .models import Contest

BEATLES = {'Джон Леннон', 'Пол Маккартни', 'Джордж Харрисон', 'Ринго Старр'}

class ContestForm(forms.ModelForm):

    def clean(self):
        super().clean()
        title = self.cleaned_data['title']
        if f'{title}' in BEATLES:
            # Отправляем письмо, если кто-то представляется 
            # именем одного из участников Beatles.
            send_mail(
                subject='Another Beatles ice cream',
                message=f'{title} ожил и пытается быть мороженым!',
                from_email='contest_form@acme.not',
                recipient_list=['admin@acme.not'],
                fail_silently=True,
            )
            raise ValidationError(
                'Мы тоже любим Битлз, но введите, пожалуйста, настоящее название мороженого!'
            ) 

    class Meta:
        model = Contest
        exclude = ('author',)
        widgets = {
            'description': forms.Textarea({'cols': '22', 'rows': '5'}),
            'comment': forms.Textarea({'cols': '22', 'rows': '5'}),
        }

Django/anfisa1sprint/anfisa_for_friends/contest/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from .forms import ContestForm
from .models import Contest


@login_required
def simple_view(request):
    return HttpResponse('Страница для залогиненных пользователей!')

def proposal(request, pk=None):
    if not request.user.is_authenticated:
        # Если пользователь не залогинен — отправляем его на страницу для входа:
        return redirect('login')
    elif pk is not None:
        instance = get_object_or_404(Contest, pk=pk)
    else:
        instance = None
    form = ContestForm(request.POST or None, instance=instance)
    context = {'form': form}
    if form.is_valid():
        form.save()
    return render(request, 'contest/form.html', context)


def delete_proposal(request, pk):
    instance = get_object_or_404(Contest, pk=pk)
    form = ContestForm(instance=instance)
    context = {'form': form}
    if request.method == 'POST':
        instance.delete()
        return redirect('contest:list')
    return render(request, 'contest/form.html', context)


def proposal_list(request):
    contest_proposals = Contest.objects.order_by('id')
    context = {'contest_proposals': contest_proposals}
    return render(request, 'contest/contest_list.html', context)

Django/anfisa1sprint/anfisa_for_friends/templates/contest/contest_list.html
{% extends "base.html" %}

{% block title %}
  Список заявок
{% endblock %}

{% block content %}
  {% for proposal in contest_proposals %}
    <div>
      {{ proposal.id }}, {{ proposal.title }}, {{ proposal.price }},
      {{ proposal.description }}{% if proposal.comment %}, {{ proposal.comment }}{% endif %}
      <br>
      <a href="{% url 'contest:edit' proposal.id %}">Редактировать заявку</a>
      |
      <a href="{% url 'contest:delete' proposal.id %}">Удалить заявку</a>
    </div>
  {% endfor %}
{% endblock %}

Django/anfisa1sprint/anfisa_for_friends/templates/contest/form.html
{% extends "base.html" %}
{% load django_bootstrap5 %}

{% block title %}
  Конкурс рецептов мороженого
{% endblock %}

{% block content %}
  {% with data=form.instance %}
    {% if "/edit/" in request.path %}
      <h2>Редактировать заявку {{ data.pk }}</h2>
    {% elif "/delete/" in request.path %}
      <h2>Удалить заявку {{ data.pk }}</h2>
    {% else %}
      <h2>Подать заявку</h2>
    {% endif %}
    <div class="card col-4">
      <div class="card-header">
        Конкурс мороженого
      </div>
      <div class="card-body">
        <form method="post">
          {% csrf_token %}
          {% if not "/delete/" in request.path %}
            {% bootstrap_form form %}
          {% else %}
            <p>{{ data.title }}</p>
            <p>{{ data.price }}</p>
            <p>{{ data.description }}</p>
            <p>{{ data.comment }}</p>
          {% endif %}
          {% bootstrap_button button_type="submit" content="Отправить" %}
        </form>
      </div>
    </div>
    {% if form.is_valid %}
      <h2>Рецепт мороженого {{ data.title }} принят на конкурс!</h2>
      <div>Номер заявки: {{ data.id }}</div>
    {% endif %}
  {% endwith %}
  <hr>
  <div>
    <a href="{% url 'contest:list' %}">Список всех заявок</a>
  </div>
{% endblock %}