Django/anfisa1sprint/anfisa_for_friends/about/urls.py
from django.urls import path
from .views import Description

app_name = 'about'

urlpatterns = [
    path('', Description.as_view(), name='description'),
]

Django/anfisa1sprint/anfisa_for_friends/anfisa_for_friends/urls.py
from django.contrib import admin
from django.contrib.auth.forms import UserCreationForm
from django.views.generic.edit import CreateView
from django.urls import include, path, reverse_lazy 
from django.conf import settings

urlpatterns = [
    path('', include('homepage.urls', namespace='homepage')),
    path('about/', include('about.urls', namespace='about')),
    path('ice_cream/', include('ice_cream.urls', namespace='ice_cream')),
    path('contest/', include('contest.urls')),
    path('admin/', admin.site.urls),
    path('auth/', include('django.contrib.auth.urls')), 
    path(
        'auth/registration/', 
        CreateView.as_view(
            template_name='registration/registration_form.html',
            form_class=UserCreationForm,
            success_url=reverse_lazy('pages:homepage'),
        ),
        name='registration',
    ),
] 

# Если проект запущен в режиме разработки...
if settings.DEBUG:
    import debug_toolbar
    # Добавить к списку urlpatterns список адресов из приложения debug_toolbar:
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),) 

Django/anfisa1sprint/anfisa_for_friends/ice_cream/urls.py
from django.urls import path

from . import views

app_name = 'ice_cream'

urlpatterns = [
    path('', views.ice_cream_list, name='ice_cream_list'),
    path('<int:pk>/', views.ice_cream_detail, name='ice_cream_detail'),
]

Django/anfisa1sprint/anfisa_for_friends/templates/includes/footer.html
<footer class="border-top text-center py-3">
  <p>© «MyKit Corp»</p>
</footer>

Django/anfisa1sprint/anfisa_for_friends/templates/includes/header.html
{% load static %}
<header>
  <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top shadow-sm">
    <div class="container">
      <div 
        class="navbar-toggler" 
        type="button" 
        data-toggle="collapse" 
        data-target="#navbarNav" 
        aria-controls="navbarNav" 
        aria-expanded="false" 
        aria-label="Toggle navigation"
        >
        <span class="navbar-toggler-icon"></span>
      </div>
      <div class="collapse navbar-collapse" id="navbarNav">
        {% with request.resolver_match.view_name as view_name %}            
        <ul class="nav nav-pills">
          <li class="nav-item">              
            <a
              class="nav-link {% if view_name == 'homepage:index' %} active {% endif %}" 
              href="{% url 'homepage:index' %}"
              >
              Главная 
            </a> 
          </li>
          <li class="nav-item">
            <a 
              class="nav-link {% if view_name == 'ice_cream:ice_cream_list' %} active {% endif %}" 
              href="{% url 'ice_cream:ice_cream_list' %}"
              >
              Каталог мороженого
            </a> 
          </li>
          <li class="nav-item">
            <a 
              class="nav-link {% if view_name == 'about:description' %} active {% endif %}"
              href="{% url 'about:description' %}"
            >
              О проекте
            </a> 
          </li>
          <li class="nav-item">
            <a
              class="nav-link {% if view_name == 'contest:create' %} active {% endif %}"
              href="{% url 'contest:create' %}"
            >
              Конкурс
            </a>
          </li> 

          {% if user.is_authenticated %}
            <span class="navbar-text">Пользователь: <b>{{ user.username }}</b></span>
            <!-- Новая кнопка -->
            <li class="nav-item">
              <a class="nav-link{% if view_name == 'password_change' %} active {% endif %}"
                href="{% url 'password_change' %}">Изменить пароль</a>
            </li>
            <li class="nav-item">
              <form method="post" action="{% url 'logout' %}" style="display: inline;">
                {% csrf_token %}
                  <button type="submit" class="nav-link btn btn-link" style="padding: 0; border: none; background: none;">
                   Выйти
                  </button>
              </form>
            </li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link{% if view_name == 'login' %} active {% endif %}" href="{% url 'login' %}">Войти</a>
            </li>
            <!-- Новая кнопка -->
            <li class="nav-item">
              <a class="nav-link{% if view_name == 'registration' %} active {% endif %}" href="{% url 'registration' %}">Регистрация</a>
            </li>
          {% endif %}
        </ul>
        {% endwith %}
      </div> 
      <a class="navbar-brand" href="{% url 'homepage:index' %}">
        <img src="{% static 'img/logo.png' %}" height="50" class="d-inline-block align-top" alt="">            
      </a>         
    </div>
  </nav>
</header>

Django/anfisa1sprint/anfisa_for_friends/templates/includes/ice_cream_card.html
{% load static %}
<div class="col-6 col-md-4 my-1">
    <div class="card">
      <img 
        class="img-fluid card-img-top" 
        height="400" width="300"
        src="{% static 'img/image-holder.png' %}"
      >
      <div class="card-body">           
        <h5 class="card-title">{{ ice_cream.title }} </h5>
        <p class="badge bg-secondary">{{ ice_cream.price }}</p>
        <p class="card-text">{{ ice_cream.description|truncatechars:40 }}</p>
        <a class="mt-3 regular-link" href="{% url 'ice_cream:ice_cream_detail' ice_cream.id %}">
          Подробнее -->
        </a>
      </div>
    </div>
  </div>